language: python

python:
  - 2.7

branches:
  only:
    - master

install:
  - pip install . --use-mirrors
  - pip install -r requirements.travis.txt --use-mirrors

script:
  - coverage run --source=predicates setup.py nosetests

after_script:
  - git clone https://github.com/coagulant/coveralls-python.git coveralls
  - cd coveralls ; python setup.py develop ; cd ..
  - coveralls/bin/coveralls --verbose
